// flow-typed signature: 0c6b57dfe8cd29a6b337fa0d352ce9db
// flow-typed version: <<STUB>>/babel-plugin-polished_v1.1.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-polished'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-polished' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-polished/index' {
  declare module.exports: $Exports<'babel-plugin-polished'>;
}
declare module 'babel-plugin-polished/index.js' {
  declare module.exports: $Exports<'babel-plugin-polished'>;
}
