// flow-typed signature: bf7c90ebdb2c0385f2ac7567d44d87f8
// flow-typed version: <<STUB>>/colorable_v1.0.5/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'colorable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'colorable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'colorable/docs/app.min' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/app' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/build' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/app' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/chip' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/color-list-item' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/color-list' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/color-preview' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/css-link-form' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/hsl-form' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/matrix-row' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/matrix' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/modal' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/radio-button' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/readme' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/super-modal' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/threshold-toggle' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/components/toolbar' {
  declare module.exports: any;
}

declare module 'colorable/docs/src/data' {
  declare module.exports: any;
}

declare module 'colorable/gulpfile' {
  declare module.exports: any;
}

declare module 'colorable/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'colorable/docs/app.min.js' {
  declare module.exports: $Exports<'colorable/docs/app.min'>;
}
declare module 'colorable/docs/src/app.js' {
  declare module.exports: $Exports<'colorable/docs/src/app'>;
}
declare module 'colorable/docs/src/build.js' {
  declare module.exports: $Exports<'colorable/docs/src/build'>;
}
declare module 'colorable/docs/src/components/app.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/app'>;
}
declare module 'colorable/docs/src/components/chip.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/chip'>;
}
declare module 'colorable/docs/src/components/color-list-item.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/color-list-item'>;
}
declare module 'colorable/docs/src/components/color-list.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/color-list'>;
}
declare module 'colorable/docs/src/components/color-preview.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/color-preview'>;
}
declare module 'colorable/docs/src/components/css-link-form.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/css-link-form'>;
}
declare module 'colorable/docs/src/components/hsl-form.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/hsl-form'>;
}
declare module 'colorable/docs/src/components/matrix-row.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/matrix-row'>;
}
declare module 'colorable/docs/src/components/matrix.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/matrix'>;
}
declare module 'colorable/docs/src/components/modal.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/modal'>;
}
declare module 'colorable/docs/src/components/radio-button.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/radio-button'>;
}
declare module 'colorable/docs/src/components/readme.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/readme'>;
}
declare module 'colorable/docs/src/components/super-modal.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/super-modal'>;
}
declare module 'colorable/docs/src/components/threshold-toggle.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/threshold-toggle'>;
}
declare module 'colorable/docs/src/components/toolbar.jsx' {
  declare module.exports: $Exports<'colorable/docs/src/components/toolbar'>;
}
declare module 'colorable/docs/src/data.js' {
  declare module.exports: $Exports<'colorable/docs/src/data'>;
}
declare module 'colorable/gulpfile.js' {
  declare module.exports: $Exports<'colorable/gulpfile'>;
}
declare module 'colorable/index' {
  declare module.exports: $Exports<'colorable'>;
}
declare module 'colorable/index.js' {
  declare module.exports: $Exports<'colorable'>;
}
declare module 'colorable/test/index.js' {
  declare module.exports: $Exports<'colorable/test/index'>;
}
