// flow-typed signature: 968e9e007ce8da143c20feeacb59ce5f
// flow-typed version: <<STUB>>/conventional-commit-types_v2.1.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'conventional-commit-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'conventional-commit-types' {
  declare module.exports: any;
}
