// flow-typed signature: d16242b8a3e77ed5229b9d599a23486b
// flow-typed version: <<STUB>>/conventional-commit-types_v2.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'conventional-commit-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'conventional-commit-types' {
  declare module.exports: any;
}
