// flow-typed signature: 0c4ec4f6b881b6167e97bf11171f4ccc
// flow-typed version: <<STUB>>/emotion-theming_v^9.2.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion-theming'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion-theming' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion-theming/dist/emotion.umd.min' {
  declare module.exports: any;
}

declare module 'emotion-theming/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'emotion-theming/dist/index.es' {
  declare module.exports: any;
}

declare module 'emotion-theming/src/channel' {
  declare module.exports: any;
}

declare module 'emotion-theming/src/create-broadcast' {
  declare module.exports: any;
}

declare module 'emotion-theming/src/index' {
  declare module.exports: any;
}

declare module 'emotion-theming/src/theme-provider' {
  declare module.exports: any;
}

declare module 'emotion-theming/src/utils' {
  declare module.exports: any;
}

declare module 'emotion-theming/src/with-theme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion-theming/dist/emotion.umd.min.js' {
  declare module.exports: $Exports<'emotion-theming/dist/emotion.umd.min'>;
}
declare module 'emotion-theming/dist/index.cjs.js' {
  declare module.exports: $Exports<'emotion-theming/dist/index.cjs'>;
}
declare module 'emotion-theming/dist/index.es.js' {
  declare module.exports: $Exports<'emotion-theming/dist/index.es'>;
}
declare module 'emotion-theming/src/channel.js' {
  declare module.exports: $Exports<'emotion-theming/src/channel'>;
}
declare module 'emotion-theming/src/create-broadcast.js' {
  declare module.exports: $Exports<'emotion-theming/src/create-broadcast'>;
}
declare module 'emotion-theming/src/index.js' {
  declare module.exports: $Exports<'emotion-theming/src/index'>;
}
declare module 'emotion-theming/src/theme-provider.js' {
  declare module.exports: $Exports<'emotion-theming/src/theme-provider'>;
}
declare module 'emotion-theming/src/utils.js' {
  declare module.exports: $Exports<'emotion-theming/src/utils'>;
}
declare module 'emotion-theming/src/with-theme.js' {
  declare module.exports: $Exports<'emotion-theming/src/with-theme'>;
}
