// flow-typed signature: 16c7cd155bfd458cb77df48c72bbb3f4
// flow-typed version: <<STUB>>/enzyme-adapter-react-16_v1.0.4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-adapter-react-16'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-adapter-react-16' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enzyme-adapter-react-16/build/findCurrentFiberUsingSlowPath' {
  declare module.exports: any;
}

declare module 'enzyme-adapter-react-16/build/index' {
  declare module.exports: any;
}

declare module 'enzyme-adapter-react-16/build/ReactSixteenAdapter' {
  declare module.exports: any;
}

declare module 'enzyme-adapter-react-16/src/findCurrentFiberUsingSlowPath' {
  declare module.exports: any;
}

declare module 'enzyme-adapter-react-16/src/index' {
  declare module.exports: any;
}

declare module 'enzyme-adapter-react-16/src/ReactSixteenAdapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enzyme-adapter-react-16/build/findCurrentFiberUsingSlowPath.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-16/build/findCurrentFiberUsingSlowPath'>;
}
declare module 'enzyme-adapter-react-16/build/index.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-16/build/index'>;
}
declare module 'enzyme-adapter-react-16/build/ReactSixteenAdapter.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-16/build/ReactSixteenAdapter'>;
}
declare module 'enzyme-adapter-react-16/src/findCurrentFiberUsingSlowPath.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-16/src/findCurrentFiberUsingSlowPath'>;
}
declare module 'enzyme-adapter-react-16/src/index.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-16/src/index'>;
}
declare module 'enzyme-adapter-react-16/src/ReactSixteenAdapter.js' {
  declare module.exports: $Exports<'enzyme-adapter-react-16/src/ReactSixteenAdapter'>;
}
