// flow-typed signature: 3b13a5c71e6d95fa26c1c485aaea3ae5
// flow-typed version: <<STUB>>/enzyme-react-adapter-future_v1.1.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-react-adapter-future'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-react-adapter-future' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enzyme-react-adapter-future/build/index' {
  declare module.exports: any;
}

declare module 'enzyme-react-adapter-future/build/ReactSixteenAdapter' {
  declare module.exports: any;
}

declare module 'enzyme-react-adapter-future/src/index' {
  declare module.exports: any;
}

declare module 'enzyme-react-adapter-future/src/ReactSixteenAdapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enzyme-react-adapter-future/build/index.js' {
  declare module.exports: $Exports<'enzyme-react-adapter-future/build/index'>;
}
declare module 'enzyme-react-adapter-future/build/ReactSixteenAdapter.js' {
  declare module.exports: $Exports<'enzyme-react-adapter-future/build/ReactSixteenAdapter'>;
}
declare module 'enzyme-react-adapter-future/src/index.js' {
  declare module.exports: $Exports<'enzyme-react-adapter-future/src/index'>;
}
declare module 'enzyme-react-adapter-future/src/ReactSixteenAdapter.js' {
  declare module.exports: $Exports<'enzyme-react-adapter-future/src/ReactSixteenAdapter'>;
}
