// flow-typed signature: dbe9c3c8f9acc62f8f60005e20a8606f
// flow-typed version: <<STUB>>/eslint-plugin-emotion_v9.1.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-emotion/src/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-emotion/src/rules/syntax-preference' {
  declare module.exports: any;
}

declare module 'eslint-plugin-emotion/test/rules/syntax-preference.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-emotion/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-emotion/src/index'>;
}
declare module 'eslint-plugin-emotion/src/rules/syntax-preference.js' {
  declare module.exports: $Exports<'eslint-plugin-emotion/src/rules/syntax-preference'>;
}
declare module 'eslint-plugin-emotion/test/rules/syntax-preference.test.js' {
  declare module.exports: $Exports<'eslint-plugin-emotion/test/rules/syntax-preference.test'>;
}
