// flow-typed signature: 18d3aafe670db7c9d1dad09b0b54f492
// flow-typed version: <<STUB>>/exenv_vlatest/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exenv/index' {
  declare module.exports: $Exports<'exenv'>;
}
declare module 'exenv/index.js' {
  declare module.exports: $Exports<'exenv'>;
}
