// flow-typed signature: 2db442d73a69de77f8020179c0dce2cc
// flow-typed version: <<STUB>>/fast-memoize_v2.3.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-memoize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-memoize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-memoize/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-memoize/src/index.js' {
  declare module.exports: $Exports<'fast-memoize/src/index'>;
}
