// flow-typed signature: f9659ef4f7065f319ab3cb48ed6baa27
// flow-typed version: <<STUB>>/fast-deep-equal_v1.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-deep-equal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-deep-equal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fast-deep-equal/index' {
  declare module.exports: $Exports<'fast-deep-equal'>;
}
declare module 'fast-deep-equal/index.js' {
  declare module.exports: $Exports<'fast-deep-equal'>;
}
