// flow-typed signature: cb4fd693d8e43bd2ede4b9344bce6085
// flow-typed version: <<STUB>>/focus-trap-react_v3.1.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'focus-trap-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'focus-trap-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'focus-trap-react/demo/js/demo-five' {
  declare module.exports: any;
}

declare module 'focus-trap-react/demo/js/demo-four' {
  declare module.exports: any;
}

declare module 'focus-trap-react/demo/js/demo-one' {
  declare module.exports: any;
}

declare module 'focus-trap-react/demo/js/demo-three' {
  declare module.exports: any;
}

declare module 'focus-trap-react/demo/js/demo-two' {
  declare module.exports: any;
}

declare module 'focus-trap-react/demo/js/index' {
  declare module.exports: any;
}

declare module 'focus-trap-react/dist/focus-trap-react' {
  declare module.exports: any;
}

declare module 'focus-trap-react/src/focus-trap-react' {
  declare module.exports: any;
}

declare module 'focus-trap-react/test/activation.test' {
  declare module.exports: any;
}

declare module 'focus-trap-react/test/deactivation.test' {
  declare module.exports: any;
}

declare module 'focus-trap-react/test/dom.test' {
  declare module.exports: any;
}

declare module 'focus-trap-react/test/jest-setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'focus-trap-react/demo/js/demo-five.js' {
  declare module.exports: $Exports<'focus-trap-react/demo/js/demo-five'>;
}
declare module 'focus-trap-react/demo/js/demo-four.js' {
  declare module.exports: $Exports<'focus-trap-react/demo/js/demo-four'>;
}
declare module 'focus-trap-react/demo/js/demo-one.js' {
  declare module.exports: $Exports<'focus-trap-react/demo/js/demo-one'>;
}
declare module 'focus-trap-react/demo/js/demo-three.js' {
  declare module.exports: $Exports<'focus-trap-react/demo/js/demo-three'>;
}
declare module 'focus-trap-react/demo/js/demo-two.js' {
  declare module.exports: $Exports<'focus-trap-react/demo/js/demo-two'>;
}
declare module 'focus-trap-react/demo/js/index.js' {
  declare module.exports: $Exports<'focus-trap-react/demo/js/index'>;
}
declare module 'focus-trap-react/dist/focus-trap-react.js' {
  declare module.exports: $Exports<'focus-trap-react/dist/focus-trap-react'>;
}
declare module 'focus-trap-react/index' {
  declare module.exports: $Exports<'focus-trap-react'>;
}
declare module 'focus-trap-react/index.js' {
  declare module.exports: $Exports<'focus-trap-react'>;
}
declare module 'focus-trap-react/src/focus-trap-react.js' {
  declare module.exports: $Exports<'focus-trap-react/src/focus-trap-react'>;
}
declare module 'focus-trap-react/test/activation.test.js' {
  declare module.exports: $Exports<'focus-trap-react/test/activation.test'>;
}
declare module 'focus-trap-react/test/deactivation.test.js' {
  declare module.exports: $Exports<'focus-trap-react/test/deactivation.test'>;
}
declare module 'focus-trap-react/test/dom.test.js' {
  declare module.exports: $Exports<'focus-trap-react/test/dom.test'>;
}
declare module 'focus-trap-react/test/jest-setup.js' {
  declare module.exports: $Exports<'focus-trap-react/test/jest-setup'>;
}
