// flow-typed signature: 355e3ea15d2835029cbb2be03ffe49e0
// flow-typed version: <<STUB>>/gh-pages_v0.12.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gh-pages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gh-pages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gh-pages/lib/git' {
  declare module.exports: any;
}

declare module 'gh-pages/lib/index' {
  declare module.exports: any;
}

declare module 'gh-pages/lib/util' {
  declare module.exports: any;
}

declare module 'gh-pages/test/helper' {
  declare module.exports: any;
}

declare module 'gh-pages/test/lib/util.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gh-pages/lib/git.js' {
  declare module.exports: $Exports<'gh-pages/lib/git'>;
}
declare module 'gh-pages/lib/index.js' {
  declare module.exports: $Exports<'gh-pages/lib/index'>;
}
declare module 'gh-pages/lib/util.js' {
  declare module.exports: $Exports<'gh-pages/lib/util'>;
}
declare module 'gh-pages/test/helper.js' {
  declare module.exports: $Exports<'gh-pages/test/helper'>;
}
declare module 'gh-pages/test/lib/util.spec.js' {
  declare module.exports: $Exports<'gh-pages/test/lib/util.spec'>;
}
