// flow-typed signature: 54ec1f062cd83e50e119bb6c5b5edc93
// flow-typed version: <<STUB>>/happo.io_v3.3.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'happo.io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'happo.io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'happo.io/build/browser/processor' {
  declare module.exports: any;
}

declare module 'happo.io/build/cli' {
  declare module.exports: any;
}

declare module 'happo.io/build/commands/compareReports' {
  declare module.exports: any;
}

declare module 'happo.io/build/commands/dev' {
  declare module.exports: any;
}

declare module 'happo.io/build/commands/hasReport' {
  declare module.exports: any;
}

declare module 'happo.io/build/commands/run' {
  declare module.exports: any;
}

declare module 'happo.io/build/constructReport' {
  declare module.exports: any;
}

declare module 'happo.io/build/createDynamicEntryPoint' {
  declare module.exports: any;
}

declare module 'happo.io/build/createHash' {
  declare module.exports: any;
}

declare module 'happo.io/build/createWebpackBundle' {
  declare module.exports: any;
}

declare module 'happo.io/build/DEFAULTS' {
  declare module.exports: any;
}

declare module 'happo.io/build/domRunner' {
  declare module.exports: any;
}

declare module 'happo.io/build/executeCli' {
  declare module.exports: any;
}

declare module 'happo.io/build/extractCSS' {
  declare module.exports: any;
}

declare module 'happo.io/build/fetchReport' {
  declare module.exports: any;
}

declare module 'happo.io/build/fileToBase64' {
  declare module.exports: any;
}

declare module 'happo.io/build/findTestFiles' {
  declare module.exports: any;
}

declare module 'happo.io/build/generateDevSha' {
  declare module.exports: any;
}

declare module 'happo.io/build/getComponentNameFromFileName' {
  declare module.exports: any;
}

declare module 'happo.io/build/index' {
  declare module.exports: any;
}

declare module 'happo.io/build/inlineCSSResources' {
  declare module.exports: any;
}

declare module 'happo.io/build/inlineResources' {
  declare module.exports: any;
}

declare module 'happo.io/build/JSDOMDomProvider' {
  declare module.exports: any;
}

declare module 'happo.io/build/loadCSSFile' {
  declare module.exports: any;
}

declare module 'happo.io/build/loadUserConfig' {
  declare module.exports: any;
}

declare module 'happo.io/build/Logger' {
  declare module.exports: any;
}

declare module 'happo.io/build/makeRequest' {
  declare module.exports: any;
}

declare module 'happo.io/build/MultipleErrors' {
  declare module.exports: any;
}

declare module 'happo.io/build/processSnapsInBundle' {
  declare module.exports: any;
}

declare module 'happo.io/build/queued' {
  declare module.exports: any;
}

declare module 'happo.io/build/RemoteBrowserTarget' {
  declare module.exports: any;
}

declare module 'happo.io/build/renderWrapper' {
  declare module.exports: any;
}

declare module 'happo.io/build/uploadReport' {
  declare module.exports: any;
}

declare module 'happo.io/build/WrappedError' {
  declare module.exports: any;
}

declare module 'happo.io/src/browser/processor' {
  declare module.exports: any;
}

declare module 'happo.io/src/cli' {
  declare module.exports: any;
}

declare module 'happo.io/src/commands/compareReports' {
  declare module.exports: any;
}

declare module 'happo.io/src/commands/dev' {
  declare module.exports: any;
}

declare module 'happo.io/src/commands/hasReport' {
  declare module.exports: any;
}

declare module 'happo.io/src/commands/run' {
  declare module.exports: any;
}

declare module 'happo.io/src/constructReport' {
  declare module.exports: any;
}

declare module 'happo.io/src/createDynamicEntryPoint' {
  declare module.exports: any;
}

declare module 'happo.io/src/createHash' {
  declare module.exports: any;
}

declare module 'happo.io/src/createWebpackBundle' {
  declare module.exports: any;
}

declare module 'happo.io/src/DEFAULTS' {
  declare module.exports: any;
}

declare module 'happo.io/src/domRunner' {
  declare module.exports: any;
}

declare module 'happo.io/src/executeCli' {
  declare module.exports: any;
}

declare module 'happo.io/src/extractCSS' {
  declare module.exports: any;
}

declare module 'happo.io/src/fetchReport' {
  declare module.exports: any;
}

declare module 'happo.io/src/fileToBase64' {
  declare module.exports: any;
}

declare module 'happo.io/src/findTestFiles' {
  declare module.exports: any;
}

declare module 'happo.io/src/generateDevSha' {
  declare module.exports: any;
}

declare module 'happo.io/src/getComponentNameFromFileName' {
  declare module.exports: any;
}

declare module 'happo.io/src/index' {
  declare module.exports: any;
}

declare module 'happo.io/src/inlineCSSResources' {
  declare module.exports: any;
}

declare module 'happo.io/src/inlineResources' {
  declare module.exports: any;
}

declare module 'happo.io/src/JSDOMDomProvider' {
  declare module.exports: any;
}

declare module 'happo.io/src/loadCSSFile' {
  declare module.exports: any;
}

declare module 'happo.io/src/loadUserConfig' {
  declare module.exports: any;
}

declare module 'happo.io/src/Logger' {
  declare module.exports: any;
}

declare module 'happo.io/src/makeRequest' {
  declare module.exports: any;
}

declare module 'happo.io/src/MultipleErrors' {
  declare module.exports: any;
}

declare module 'happo.io/src/processSnapsInBundle' {
  declare module.exports: any;
}

declare module 'happo.io/src/queued' {
  declare module.exports: any;
}

declare module 'happo.io/src/RemoteBrowserTarget' {
  declare module.exports: any;
}

declare module 'happo.io/src/renderWrapper' {
  declare module.exports: any;
}

declare module 'happo.io/src/uploadReport' {
  declare module.exports: any;
}

declare module 'happo.io/src/WrappedError' {
  declare module.exports: any;
}

declare module 'happo.io/test/executeCli-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/getComponentNameFromFileName-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/inlineCSSResources-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/inlineResources-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/error-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/examples/Bar-react-happo' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/examples/dynamically-imported' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/examples/Foo-error-happo' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/examples/Foo-plain-happo' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/examples/Foo-react-happo' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/MockTarget' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/plain-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/plugin-examples' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/react-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/reactSetup' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/renderWrapper' {
  declare module.exports: any;
}

declare module 'happo.io/test/integrations/theme' {
  declare module.exports: any;
}

declare module 'happo.io/test/jestSetup' {
  declare module.exports: any;
}

declare module 'happo.io/test/loadUserConfig-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/Logger-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/queued-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/RemoteBrowserTarget-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'happo.io/build/browser/processor.js' {
  declare module.exports: $Exports<'happo.io/build/browser/processor'>;
}
declare module 'happo.io/build/cli.js' {
  declare module.exports: $Exports<'happo.io/build/cli'>;
}
declare module 'happo.io/build/commands/compareReports.js' {
  declare module.exports: $Exports<'happo.io/build/commands/compareReports'>;
}
declare module 'happo.io/build/commands/dev.js' {
  declare module.exports: $Exports<'happo.io/build/commands/dev'>;
}
declare module 'happo.io/build/commands/hasReport.js' {
  declare module.exports: $Exports<'happo.io/build/commands/hasReport'>;
}
declare module 'happo.io/build/commands/run.js' {
  declare module.exports: $Exports<'happo.io/build/commands/run'>;
}
declare module 'happo.io/build/constructReport.js' {
  declare module.exports: $Exports<'happo.io/build/constructReport'>;
}
declare module 'happo.io/build/createDynamicEntryPoint.js' {
  declare module.exports: $Exports<'happo.io/build/createDynamicEntryPoint'>;
}
declare module 'happo.io/build/createHash.js' {
  declare module.exports: $Exports<'happo.io/build/createHash'>;
}
declare module 'happo.io/build/createWebpackBundle.js' {
  declare module.exports: $Exports<'happo.io/build/createWebpackBundle'>;
}
declare module 'happo.io/build/DEFAULTS.js' {
  declare module.exports: $Exports<'happo.io/build/DEFAULTS'>;
}
declare module 'happo.io/build/domRunner.js' {
  declare module.exports: $Exports<'happo.io/build/domRunner'>;
}
declare module 'happo.io/build/executeCli.js' {
  declare module.exports: $Exports<'happo.io/build/executeCli'>;
}
declare module 'happo.io/build/extractCSS.js' {
  declare module.exports: $Exports<'happo.io/build/extractCSS'>;
}
declare module 'happo.io/build/fetchReport.js' {
  declare module.exports: $Exports<'happo.io/build/fetchReport'>;
}
declare module 'happo.io/build/fileToBase64.js' {
  declare module.exports: $Exports<'happo.io/build/fileToBase64'>;
}
declare module 'happo.io/build/findTestFiles.js' {
  declare module.exports: $Exports<'happo.io/build/findTestFiles'>;
}
declare module 'happo.io/build/generateDevSha.js' {
  declare module.exports: $Exports<'happo.io/build/generateDevSha'>;
}
declare module 'happo.io/build/getComponentNameFromFileName.js' {
  declare module.exports: $Exports<'happo.io/build/getComponentNameFromFileName'>;
}
declare module 'happo.io/build/index.js' {
  declare module.exports: $Exports<'happo.io/build/index'>;
}
declare module 'happo.io/build/inlineCSSResources.js' {
  declare module.exports: $Exports<'happo.io/build/inlineCSSResources'>;
}
declare module 'happo.io/build/inlineResources.js' {
  declare module.exports: $Exports<'happo.io/build/inlineResources'>;
}
declare module 'happo.io/build/JSDOMDomProvider.js' {
  declare module.exports: $Exports<'happo.io/build/JSDOMDomProvider'>;
}
declare module 'happo.io/build/loadCSSFile.js' {
  declare module.exports: $Exports<'happo.io/build/loadCSSFile'>;
}
declare module 'happo.io/build/loadUserConfig.js' {
  declare module.exports: $Exports<'happo.io/build/loadUserConfig'>;
}
declare module 'happo.io/build/Logger.js' {
  declare module.exports: $Exports<'happo.io/build/Logger'>;
}
declare module 'happo.io/build/makeRequest.js' {
  declare module.exports: $Exports<'happo.io/build/makeRequest'>;
}
declare module 'happo.io/build/MultipleErrors.js' {
  declare module.exports: $Exports<'happo.io/build/MultipleErrors'>;
}
declare module 'happo.io/build/processSnapsInBundle.js' {
  declare module.exports: $Exports<'happo.io/build/processSnapsInBundle'>;
}
declare module 'happo.io/build/queued.js' {
  declare module.exports: $Exports<'happo.io/build/queued'>;
}
declare module 'happo.io/build/RemoteBrowserTarget.js' {
  declare module.exports: $Exports<'happo.io/build/RemoteBrowserTarget'>;
}
declare module 'happo.io/build/renderWrapper.js' {
  declare module.exports: $Exports<'happo.io/build/renderWrapper'>;
}
declare module 'happo.io/build/uploadReport.js' {
  declare module.exports: $Exports<'happo.io/build/uploadReport'>;
}
declare module 'happo.io/build/WrappedError.js' {
  declare module.exports: $Exports<'happo.io/build/WrappedError'>;
}
declare module 'happo.io/src/browser/processor.js' {
  declare module.exports: $Exports<'happo.io/src/browser/processor'>;
}
declare module 'happo.io/src/cli.js' {
  declare module.exports: $Exports<'happo.io/src/cli'>;
}
declare module 'happo.io/src/commands/compareReports.js' {
  declare module.exports: $Exports<'happo.io/src/commands/compareReports'>;
}
declare module 'happo.io/src/commands/dev.js' {
  declare module.exports: $Exports<'happo.io/src/commands/dev'>;
}
declare module 'happo.io/src/commands/hasReport.js' {
  declare module.exports: $Exports<'happo.io/src/commands/hasReport'>;
}
declare module 'happo.io/src/commands/run.js' {
  declare module.exports: $Exports<'happo.io/src/commands/run'>;
}
declare module 'happo.io/src/constructReport.js' {
  declare module.exports: $Exports<'happo.io/src/constructReport'>;
}
declare module 'happo.io/src/createDynamicEntryPoint.js' {
  declare module.exports: $Exports<'happo.io/src/createDynamicEntryPoint'>;
}
declare module 'happo.io/src/createHash.js' {
  declare module.exports: $Exports<'happo.io/src/createHash'>;
}
declare module 'happo.io/src/createWebpackBundle.js' {
  declare module.exports: $Exports<'happo.io/src/createWebpackBundle'>;
}
declare module 'happo.io/src/DEFAULTS.js' {
  declare module.exports: $Exports<'happo.io/src/DEFAULTS'>;
}
declare module 'happo.io/src/domRunner.js' {
  declare module.exports: $Exports<'happo.io/src/domRunner'>;
}
declare module 'happo.io/src/executeCli.js' {
  declare module.exports: $Exports<'happo.io/src/executeCli'>;
}
declare module 'happo.io/src/extractCSS.js' {
  declare module.exports: $Exports<'happo.io/src/extractCSS'>;
}
declare module 'happo.io/src/fetchReport.js' {
  declare module.exports: $Exports<'happo.io/src/fetchReport'>;
}
declare module 'happo.io/src/fileToBase64.js' {
  declare module.exports: $Exports<'happo.io/src/fileToBase64'>;
}
declare module 'happo.io/src/findTestFiles.js' {
  declare module.exports: $Exports<'happo.io/src/findTestFiles'>;
}
declare module 'happo.io/src/generateDevSha.js' {
  declare module.exports: $Exports<'happo.io/src/generateDevSha'>;
}
declare module 'happo.io/src/getComponentNameFromFileName.js' {
  declare module.exports: $Exports<'happo.io/src/getComponentNameFromFileName'>;
}
declare module 'happo.io/src/index.js' {
  declare module.exports: $Exports<'happo.io/src/index'>;
}
declare module 'happo.io/src/inlineCSSResources.js' {
  declare module.exports: $Exports<'happo.io/src/inlineCSSResources'>;
}
declare module 'happo.io/src/inlineResources.js' {
  declare module.exports: $Exports<'happo.io/src/inlineResources'>;
}
declare module 'happo.io/src/JSDOMDomProvider.js' {
  declare module.exports: $Exports<'happo.io/src/JSDOMDomProvider'>;
}
declare module 'happo.io/src/loadCSSFile.js' {
  declare module.exports: $Exports<'happo.io/src/loadCSSFile'>;
}
declare module 'happo.io/src/loadUserConfig.js' {
  declare module.exports: $Exports<'happo.io/src/loadUserConfig'>;
}
declare module 'happo.io/src/Logger.js' {
  declare module.exports: $Exports<'happo.io/src/Logger'>;
}
declare module 'happo.io/src/makeRequest.js' {
  declare module.exports: $Exports<'happo.io/src/makeRequest'>;
}
declare module 'happo.io/src/MultipleErrors.js' {
  declare module.exports: $Exports<'happo.io/src/MultipleErrors'>;
}
declare module 'happo.io/src/processSnapsInBundle.js' {
  declare module.exports: $Exports<'happo.io/src/processSnapsInBundle'>;
}
declare module 'happo.io/src/queued.js' {
  declare module.exports: $Exports<'happo.io/src/queued'>;
}
declare module 'happo.io/src/RemoteBrowserTarget.js' {
  declare module.exports: $Exports<'happo.io/src/RemoteBrowserTarget'>;
}
declare module 'happo.io/src/renderWrapper.js' {
  declare module.exports: $Exports<'happo.io/src/renderWrapper'>;
}
declare module 'happo.io/src/uploadReport.js' {
  declare module.exports: $Exports<'happo.io/src/uploadReport'>;
}
declare module 'happo.io/src/WrappedError.js' {
  declare module.exports: $Exports<'happo.io/src/WrappedError'>;
}
declare module 'happo.io/test/executeCli-test.js' {
  declare module.exports: $Exports<'happo.io/test/executeCli-test'>;
}
declare module 'happo.io/test/getComponentNameFromFileName-test.js' {
  declare module.exports: $Exports<'happo.io/test/getComponentNameFromFileName-test'>;
}
declare module 'happo.io/test/inlineCSSResources-test.js' {
  declare module.exports: $Exports<'happo.io/test/inlineCSSResources-test'>;
}
declare module 'happo.io/test/inlineResources-test.js' {
  declare module.exports: $Exports<'happo.io/test/inlineResources-test'>;
}
declare module 'happo.io/test/integrations/error-test.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/error-test'>;
}
declare module 'happo.io/test/integrations/examples/Bar-react-happo.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/examples/Bar-react-happo'>;
}
declare module 'happo.io/test/integrations/examples/dynamically-imported.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/examples/dynamically-imported'>;
}
declare module 'happo.io/test/integrations/examples/Foo-error-happo.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/examples/Foo-error-happo'>;
}
declare module 'happo.io/test/integrations/examples/Foo-plain-happo.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/examples/Foo-plain-happo'>;
}
declare module 'happo.io/test/integrations/examples/Foo-react-happo.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/examples/Foo-react-happo'>;
}
declare module 'happo.io/test/integrations/MockTarget.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/MockTarget'>;
}
declare module 'happo.io/test/integrations/plain-test.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/plain-test'>;
}
declare module 'happo.io/test/integrations/plugin-examples.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/plugin-examples'>;
}
declare module 'happo.io/test/integrations/react-test.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/react-test'>;
}
declare module 'happo.io/test/integrations/reactSetup.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/reactSetup'>;
}
declare module 'happo.io/test/integrations/renderWrapper.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/renderWrapper'>;
}
declare module 'happo.io/test/integrations/theme.js' {
  declare module.exports: $Exports<'happo.io/test/integrations/theme'>;
}
declare module 'happo.io/test/jestSetup.js' {
  declare module.exports: $Exports<'happo.io/test/jestSetup'>;
}
declare module 'happo.io/test/loadUserConfig-test.js' {
  declare module.exports: $Exports<'happo.io/test/loadUserConfig-test'>;
}
declare module 'happo.io/test/Logger-test.js' {
  declare module.exports: $Exports<'happo.io/test/Logger-test'>;
}
declare module 'happo.io/test/queued-test.js' {
  declare module.exports: $Exports<'happo.io/test/queued-test'>;
}
declare module 'happo.io/test/RemoteBrowserTarget-test.js' {
  declare module.exports: $Exports<'happo.io/test/RemoteBrowserTarget-test'>;
}
