// flow-typed signature: 58073d27465d66b1f033d9faf1f3b0f8
// flow-typed version: <<STUB>>/happo-plugin-puppeteer_v1.1.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'happo-plugin-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'happo-plugin-puppeteer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'happo-plugin-puppeteer/PuppeteerDomProvider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'happo-plugin-puppeteer/index' {
  declare module.exports: $Exports<'happo-plugin-puppeteer'>;
}
declare module 'happo-plugin-puppeteer/index.js' {
  declare module.exports: $Exports<'happo-plugin-puppeteer'>;
}
declare module 'happo-plugin-puppeteer/PuppeteerDomProvider.js' {
  declare module.exports: $Exports<'happo-plugin-puppeteer/PuppeteerDomProvider'>;
}
