// flow-typed signature: 7431dc69dfd568aefc6f90f830471ce3
// flow-typed version: <<STUB>>/happo.io_v1.0.0-rc1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'happo.io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'happo.io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'happo.io/build/assumedPromise' {
  declare module.exports: any;
}

declare module 'happo.io/build/cli' {
  declare module.exports: any;
}

declare module 'happo.io/build/commands/compareReports' {
  declare module.exports: any;
}

declare module 'happo.io/build/commands/dev' {
  declare module.exports: any;
}

declare module 'happo.io/build/commands/hasReport' {
  declare module.exports: any;
}

declare module 'happo.io/build/commands/run' {
  declare module.exports: any;
}

declare module 'happo.io/build/constructReport' {
  declare module.exports: any;
}

declare module 'happo.io/build/createDynamicEntryPoint' {
  declare module.exports: any;
}

declare module 'happo.io/build/createHash' {
  declare module.exports: any;
}

declare module 'happo.io/build/createWebpackBundle' {
  declare module.exports: any;
}

declare module 'happo.io/build/DEFAULTS' {
  declare module.exports: any;
}

declare module 'happo.io/build/extractCSS' {
  declare module.exports: any;
}

declare module 'happo.io/build/fetchReport' {
  declare module.exports: any;
}

declare module 'happo.io/build/findRepository' {
  declare module.exports: any;
}

declare module 'happo.io/build/findTestFiles' {
  declare module.exports: any;
}

declare module 'happo.io/build/generateDevSha' {
  declare module.exports: any;
}

declare module 'happo.io/build/getComponentNameFromFileName' {
  declare module.exports: any;
}

declare module 'happo.io/build/getCurrentSnapshots' {
  declare module.exports: any;
}

declare module 'happo.io/build/getPreviousSha' {
  declare module.exports: any;
}

declare module 'happo.io/build/getReport' {
  declare module.exports: any;
}

declare module 'happo.io/build/getSha' {
  declare module.exports: any;
}

declare module 'happo.io/build/index' {
  declare module.exports: any;
}

declare module 'happo.io/build/inlineResources' {
  declare module.exports: any;
}

declare module 'happo.io/build/loadCSSFile' {
  declare module.exports: any;
}

declare module 'happo.io/build/loadUserConfig' {
  declare module.exports: any;
}

declare module 'happo.io/build/makeRequest' {
  declare module.exports: any;
}

declare module 'happo.io/build/moveToSha' {
  declare module.exports: any;
}

declare module 'happo.io/build/PreviewServer' {
  declare module.exports: any;
}

declare module 'happo.io/build/previousSha' {
  declare module.exports: any;
}

declare module 'happo.io/build/processSnap' {
  declare module.exports: any;
}

declare module 'happo.io/build/processSnapsInBundle' {
  declare module.exports: any;
}

declare module 'happo.io/build/queued' {
  declare module.exports: any;
}

declare module 'happo.io/build/reactDOMRunner' {
  declare module.exports: any;
}

declare module 'happo.io/build/RemoteBrowserTarget' {
  declare module.exports: any;
}

declare module 'happo.io/build/resolveTestName' {
  declare module.exports: any;
}

declare module 'happo.io/build/runCommand' {
  declare module.exports: any;
}

declare module 'happo.io/build/runForSha' {
  declare module.exports: any;
}

declare module 'happo.io/build/saveCurrentSnapshots' {
  declare module.exports: any;
}

declare module 'happo.io/build/saveReport' {
  declare module.exports: any;
}

declare module 'happo.io/build/snap' {
  declare module.exports: any;
}

declare module 'happo.io/build/test/snap-test' {
  declare module.exports: any;
}

declare module 'happo.io/build/testName' {
  declare module.exports: any;
}

declare module 'happo.io/build/uploadReport' {
  declare module.exports: any;
}

declare module 'happo.io/build/webpackEntry' {
  declare module.exports: any;
}

declare module 'happo.io/build/withJSDom' {
  declare module.exports: any;
}

declare module 'happo.io/src/cli' {
  declare module.exports: any;
}

declare module 'happo.io/src/commands/compareReports' {
  declare module.exports: any;
}

declare module 'happo.io/src/commands/dev' {
  declare module.exports: any;
}

declare module 'happo.io/src/commands/hasReport' {
  declare module.exports: any;
}

declare module 'happo.io/src/commands/run' {
  declare module.exports: any;
}

declare module 'happo.io/src/constructReport' {
  declare module.exports: any;
}

declare module 'happo.io/src/createDynamicEntryPoint' {
  declare module.exports: any;
}

declare module 'happo.io/src/createHash' {
  declare module.exports: any;
}

declare module 'happo.io/src/createWebpackBundle' {
  declare module.exports: any;
}

declare module 'happo.io/src/DEFAULTS' {
  declare module.exports: any;
}

declare module 'happo.io/src/extractCSS' {
  declare module.exports: any;
}

declare module 'happo.io/src/fetchReport' {
  declare module.exports: any;
}

declare module 'happo.io/src/findRepository' {
  declare module.exports: any;
}

declare module 'happo.io/src/findTestFiles' {
  declare module.exports: any;
}

declare module 'happo.io/src/generateDevSha' {
  declare module.exports: any;
}

declare module 'happo.io/src/getComponentNameFromFileName' {
  declare module.exports: any;
}

declare module 'happo.io/src/index' {
  declare module.exports: any;
}

declare module 'happo.io/src/inlineResources' {
  declare module.exports: any;
}

declare module 'happo.io/src/loadCSSFile' {
  declare module.exports: any;
}

declare module 'happo.io/src/loadUserConfig' {
  declare module.exports: any;
}

declare module 'happo.io/src/makeRequest' {
  declare module.exports: any;
}

declare module 'happo.io/src/processSnapsInBundle' {
  declare module.exports: any;
}

declare module 'happo.io/src/queued' {
  declare module.exports: any;
}

declare module 'happo.io/src/reactDOMRunner' {
  declare module.exports: any;
}

declare module 'happo.io/src/RemoteBrowserTarget' {
  declare module.exports: any;
}

declare module 'happo.io/src/uploadReport' {
  declare module.exports: any;
}

declare module 'happo.io/test/getComponentNameFromFileName-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/inlineResources-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/loadUserConfig-test' {
  declare module.exports: any;
}

declare module 'happo.io/test/queued-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'happo.io/build/assumedPromise.js' {
  declare module.exports: $Exports<'happo.io/build/assumedPromise'>;
}
declare module 'happo.io/build/cli.js' {
  declare module.exports: $Exports<'happo.io/build/cli'>;
}
declare module 'happo.io/build/commands/compareReports.js' {
  declare module.exports: $Exports<'happo.io/build/commands/compareReports'>;
}
declare module 'happo.io/build/commands/dev.js' {
  declare module.exports: $Exports<'happo.io/build/commands/dev'>;
}
declare module 'happo.io/build/commands/hasReport.js' {
  declare module.exports: $Exports<'happo.io/build/commands/hasReport'>;
}
declare module 'happo.io/build/commands/run.js' {
  declare module.exports: $Exports<'happo.io/build/commands/run'>;
}
declare module 'happo.io/build/constructReport.js' {
  declare module.exports: $Exports<'happo.io/build/constructReport'>;
}
declare module 'happo.io/build/createDynamicEntryPoint.js' {
  declare module.exports: $Exports<'happo.io/build/createDynamicEntryPoint'>;
}
declare module 'happo.io/build/createHash.js' {
  declare module.exports: $Exports<'happo.io/build/createHash'>;
}
declare module 'happo.io/build/createWebpackBundle.js' {
  declare module.exports: $Exports<'happo.io/build/createWebpackBundle'>;
}
declare module 'happo.io/build/DEFAULTS.js' {
  declare module.exports: $Exports<'happo.io/build/DEFAULTS'>;
}
declare module 'happo.io/build/extractCSS.js' {
  declare module.exports: $Exports<'happo.io/build/extractCSS'>;
}
declare module 'happo.io/build/fetchReport.js' {
  declare module.exports: $Exports<'happo.io/build/fetchReport'>;
}
declare module 'happo.io/build/findRepository.js' {
  declare module.exports: $Exports<'happo.io/build/findRepository'>;
}
declare module 'happo.io/build/findTestFiles.js' {
  declare module.exports: $Exports<'happo.io/build/findTestFiles'>;
}
declare module 'happo.io/build/generateDevSha.js' {
  declare module.exports: $Exports<'happo.io/build/generateDevSha'>;
}
declare module 'happo.io/build/getComponentNameFromFileName.js' {
  declare module.exports: $Exports<'happo.io/build/getComponentNameFromFileName'>;
}
declare module 'happo.io/build/getCurrentSnapshots.js' {
  declare module.exports: $Exports<'happo.io/build/getCurrentSnapshots'>;
}
declare module 'happo.io/build/getPreviousSha.js' {
  declare module.exports: $Exports<'happo.io/build/getPreviousSha'>;
}
declare module 'happo.io/build/getReport.js' {
  declare module.exports: $Exports<'happo.io/build/getReport'>;
}
declare module 'happo.io/build/getSha.js' {
  declare module.exports: $Exports<'happo.io/build/getSha'>;
}
declare module 'happo.io/build/index.js' {
  declare module.exports: $Exports<'happo.io/build/index'>;
}
declare module 'happo.io/build/inlineResources.js' {
  declare module.exports: $Exports<'happo.io/build/inlineResources'>;
}
declare module 'happo.io/build/loadCSSFile.js' {
  declare module.exports: $Exports<'happo.io/build/loadCSSFile'>;
}
declare module 'happo.io/build/loadUserConfig.js' {
  declare module.exports: $Exports<'happo.io/build/loadUserConfig'>;
}
declare module 'happo.io/build/makeRequest.js' {
  declare module.exports: $Exports<'happo.io/build/makeRequest'>;
}
declare module 'happo.io/build/moveToSha.js' {
  declare module.exports: $Exports<'happo.io/build/moveToSha'>;
}
declare module 'happo.io/build/PreviewServer.js' {
  declare module.exports: $Exports<'happo.io/build/PreviewServer'>;
}
declare module 'happo.io/build/previousSha.js' {
  declare module.exports: $Exports<'happo.io/build/previousSha'>;
}
declare module 'happo.io/build/processSnap.js' {
  declare module.exports: $Exports<'happo.io/build/processSnap'>;
}
declare module 'happo.io/build/processSnapsInBundle.js' {
  declare module.exports: $Exports<'happo.io/build/processSnapsInBundle'>;
}
declare module 'happo.io/build/queued.js' {
  declare module.exports: $Exports<'happo.io/build/queued'>;
}
declare module 'happo.io/build/reactDOMRunner.js' {
  declare module.exports: $Exports<'happo.io/build/reactDOMRunner'>;
}
declare module 'happo.io/build/RemoteBrowserTarget.js' {
  declare module.exports: $Exports<'happo.io/build/RemoteBrowserTarget'>;
}
declare module 'happo.io/build/resolveTestName.js' {
  declare module.exports: $Exports<'happo.io/build/resolveTestName'>;
}
declare module 'happo.io/build/runCommand.js' {
  declare module.exports: $Exports<'happo.io/build/runCommand'>;
}
declare module 'happo.io/build/runForSha.js' {
  declare module.exports: $Exports<'happo.io/build/runForSha'>;
}
declare module 'happo.io/build/saveCurrentSnapshots.js' {
  declare module.exports: $Exports<'happo.io/build/saveCurrentSnapshots'>;
}
declare module 'happo.io/build/saveReport.js' {
  declare module.exports: $Exports<'happo.io/build/saveReport'>;
}
declare module 'happo.io/build/snap.js' {
  declare module.exports: $Exports<'happo.io/build/snap'>;
}
declare module 'happo.io/build/test/snap-test.js' {
  declare module.exports: $Exports<'happo.io/build/test/snap-test'>;
}
declare module 'happo.io/build/testName.js' {
  declare module.exports: $Exports<'happo.io/build/testName'>;
}
declare module 'happo.io/build/uploadReport.js' {
  declare module.exports: $Exports<'happo.io/build/uploadReport'>;
}
declare module 'happo.io/build/webpackEntry.js' {
  declare module.exports: $Exports<'happo.io/build/webpackEntry'>;
}
declare module 'happo.io/build/withJSDom.js' {
  declare module.exports: $Exports<'happo.io/build/withJSDom'>;
}
declare module 'happo.io/src/cli.js' {
  declare module.exports: $Exports<'happo.io/src/cli'>;
}
declare module 'happo.io/src/commands/compareReports.js' {
  declare module.exports: $Exports<'happo.io/src/commands/compareReports'>;
}
declare module 'happo.io/src/commands/dev.js' {
  declare module.exports: $Exports<'happo.io/src/commands/dev'>;
}
declare module 'happo.io/src/commands/hasReport.js' {
  declare module.exports: $Exports<'happo.io/src/commands/hasReport'>;
}
declare module 'happo.io/src/commands/run.js' {
  declare module.exports: $Exports<'happo.io/src/commands/run'>;
}
declare module 'happo.io/src/constructReport.js' {
  declare module.exports: $Exports<'happo.io/src/constructReport'>;
}
declare module 'happo.io/src/createDynamicEntryPoint.js' {
  declare module.exports: $Exports<'happo.io/src/createDynamicEntryPoint'>;
}
declare module 'happo.io/src/createHash.js' {
  declare module.exports: $Exports<'happo.io/src/createHash'>;
}
declare module 'happo.io/src/createWebpackBundle.js' {
  declare module.exports: $Exports<'happo.io/src/createWebpackBundle'>;
}
declare module 'happo.io/src/DEFAULTS.js' {
  declare module.exports: $Exports<'happo.io/src/DEFAULTS'>;
}
declare module 'happo.io/src/extractCSS.js' {
  declare module.exports: $Exports<'happo.io/src/extractCSS'>;
}
declare module 'happo.io/src/fetchReport.js' {
  declare module.exports: $Exports<'happo.io/src/fetchReport'>;
}
declare module 'happo.io/src/findRepository.js' {
  declare module.exports: $Exports<'happo.io/src/findRepository'>;
}
declare module 'happo.io/src/findTestFiles.js' {
  declare module.exports: $Exports<'happo.io/src/findTestFiles'>;
}
declare module 'happo.io/src/generateDevSha.js' {
  declare module.exports: $Exports<'happo.io/src/generateDevSha'>;
}
declare module 'happo.io/src/getComponentNameFromFileName.js' {
  declare module.exports: $Exports<'happo.io/src/getComponentNameFromFileName'>;
}
declare module 'happo.io/src/index.js' {
  declare module.exports: $Exports<'happo.io/src/index'>;
}
declare module 'happo.io/src/inlineResources.js' {
  declare module.exports: $Exports<'happo.io/src/inlineResources'>;
}
declare module 'happo.io/src/loadCSSFile.js' {
  declare module.exports: $Exports<'happo.io/src/loadCSSFile'>;
}
declare module 'happo.io/src/loadUserConfig.js' {
  declare module.exports: $Exports<'happo.io/src/loadUserConfig'>;
}
declare module 'happo.io/src/makeRequest.js' {
  declare module.exports: $Exports<'happo.io/src/makeRequest'>;
}
declare module 'happo.io/src/processSnapsInBundle.js' {
  declare module.exports: $Exports<'happo.io/src/processSnapsInBundle'>;
}
declare module 'happo.io/src/queued.js' {
  declare module.exports: $Exports<'happo.io/src/queued'>;
}
declare module 'happo.io/src/reactDOMRunner.js' {
  declare module.exports: $Exports<'happo.io/src/reactDOMRunner'>;
}
declare module 'happo.io/src/RemoteBrowserTarget.js' {
  declare module.exports: $Exports<'happo.io/src/RemoteBrowserTarget'>;
}
declare module 'happo.io/src/uploadReport.js' {
  declare module.exports: $Exports<'happo.io/src/uploadReport'>;
}
declare module 'happo.io/test/getComponentNameFromFileName-test.js' {
  declare module.exports: $Exports<'happo.io/test/getComponentNameFromFileName-test'>;
}
declare module 'happo.io/test/inlineResources-test.js' {
  declare module.exports: $Exports<'happo.io/test/inlineResources-test'>;
}
declare module 'happo.io/test/loadUserConfig-test.js' {
  declare module.exports: $Exports<'happo.io/test/loadUserConfig-test'>;
}
declare module 'happo.io/test/queued-test.js' {
  declare module.exports: $Exports<'happo.io/test/queued-test'>;
}
