// flow-typed signature: 3e115c9bbaa2e0f2ed8a85fee7793c02
// flow-typed version: <<STUB>>/jaybe-react-loadable_v5.6.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jaybe-react-loadable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jaybe-react-loadable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jaybe-react-loadable/babel' {
  declare module.exports: any;
}

declare module 'jaybe-react-loadable/lib/babel' {
  declare module.exports: any;
}

declare module 'jaybe-react-loadable/lib/index' {
  declare module.exports: any;
}

declare module 'jaybe-react-loadable/lib/webpack' {
  declare module.exports: any;
}

declare module 'jaybe-react-loadable/webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jaybe-react-loadable/babel.js' {
  declare module.exports: $Exports<'jaybe-react-loadable/babel'>;
}
declare module 'jaybe-react-loadable/lib/babel.js' {
  declare module.exports: $Exports<'jaybe-react-loadable/lib/babel'>;
}
declare module 'jaybe-react-loadable/lib/index.js' {
  declare module.exports: $Exports<'jaybe-react-loadable/lib/index'>;
}
declare module 'jaybe-react-loadable/lib/webpack.js' {
  declare module.exports: $Exports<'jaybe-react-loadable/lib/webpack'>;
}
declare module 'jaybe-react-loadable/webpack.js' {
  declare module.exports: $Exports<'jaybe-react-loadable/webpack'>;
}
