// flow-typed signature: 728e19ff8d8c21a40c28f3b1a170a254
// flow-typed version: <<STUB>>/jest-glamor-react_v1.4.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-glamor-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-glamor-react' {
  declare module.exports: any;

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
}
declare module 'jest-glamor-react/dist/index' {
  declare module.exports: any;
}
declare module 'jest-glamor-react/dist/matcher' {
  declare module.exports: any;
}
declare module 'jest-glamor-react/dist/serializer' {
  declare module.exports: any;

  // Filename aliases
}
declare module 'jest-glamor-react/dist/index.js' {
  declare module.exports: $Exports<'jest-glamor-react/dist/index'>;
}
declare module 'jest-glamor-react/dist/matcher.js' {
  declare module.exports: $Exports<'jest-glamor-react/dist/matcher'>;
}
declare module 'jest-glamor-react/dist/serializer.js' {
  declare module.exports: $Exports<'jest-glamor-react/dist/serializer'>;
}
