// flow-typed signature: 3ccb7681dc9d3e9abdab842d8a16c21d
// flow-typed version: <<STUB>>/jest-emotion_v9.2.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-emotion/lib/index' {
  declare module.exports: any;
}

declare module 'jest-emotion/lib/matchers' {
  declare module.exports: any;
}

declare module 'jest-emotion/lib/replace-class-names' {
  declare module.exports: any;
}

declare module 'jest-emotion/lib/utils' {
  declare module.exports: any;
}

declare module 'jest-emotion/src/index' {
  declare module.exports: any;
}

declare module 'jest-emotion/src/matchers' {
  declare module.exports: any;
}

declare module 'jest-emotion/src/replace-class-names' {
  declare module.exports: any;
}

declare module 'jest-emotion/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-emotion/lib/index.js' {
  declare module.exports: $Exports<'jest-emotion/lib/index'>;
}
declare module 'jest-emotion/lib/matchers.js' {
  declare module.exports: $Exports<'jest-emotion/lib/matchers'>;
}
declare module 'jest-emotion/lib/replace-class-names.js' {
  declare module.exports: $Exports<'jest-emotion/lib/replace-class-names'>;
}
declare module 'jest-emotion/lib/utils.js' {
  declare module.exports: $Exports<'jest-emotion/lib/utils'>;
}
declare module 'jest-emotion/src/index.js' {
  declare module.exports: $Exports<'jest-emotion/src/index'>;
}
declare module 'jest-emotion/src/matchers.js' {
  declare module.exports: $Exports<'jest-emotion/src/matchers'>;
}
declare module 'jest-emotion/src/replace-class-names.js' {
  declare module.exports: $Exports<'jest-emotion/src/replace-class-names'>;
}
declare module 'jest-emotion/src/utils.js' {
  declare module.exports: $Exports<'jest-emotion/src/utils'>;
}
