// flow-typed signature: c45901425598e7a35867f85aefc7cb5c
// flow-typed version: <<STUB>>/link-parent-bin_v0.1.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'link-parent-bin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'link-parent-bin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'link-parent-bin/src/cli' {
  declare module.exports: any;
}

declare module 'link-parent-bin/src/FSUtils' {
  declare module.exports: any;
}

declare module 'link-parent-bin/src/link' {
  declare module.exports: any;
}

declare module 'link-parent-bin/src/ParentBinLinker' {
  declare module.exports: any;
}

declare module 'link-parent-bin/src/program' {
  declare module.exports: any;
}

// Filename aliases
declare module 'link-parent-bin/src/cli.js' {
  declare module.exports: $Exports<'link-parent-bin/src/cli'>;
}
declare module 'link-parent-bin/src/FSUtils.js' {
  declare module.exports: $Exports<'link-parent-bin/src/FSUtils'>;
}
declare module 'link-parent-bin/src/link.js' {
  declare module.exports: $Exports<'link-parent-bin/src/link'>;
}
declare module 'link-parent-bin/src/ParentBinLinker.js' {
  declare module.exports: $Exports<'link-parent-bin/src/ParentBinLinker'>;
}
declare module 'link-parent-bin/src/program.js' {
  declare module.exports: $Exports<'link-parent-bin/src/program'>;
}
