// flow-typed signature: e4e484f96b3f576a9d76968eb84fc282
// flow-typed version: <<STUB>>/lodash.upperfirst_v4.3.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.upperfirst'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.upperfirst' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.upperfirst/index' {
  declare module.exports: $Exports<'lodash.upperfirst'>;
}
declare module 'lodash.upperfirst/index.js' {
  declare module.exports: $Exports<'lodash.upperfirst'>;
}
