// flow-typed signature: 2e5506e6394829809cc89f947894e09b
// flow-typed version: <<STUB>>/lodash.camelcase_v4.3.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.camelcase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.camelcase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.camelcase/index' {
  declare module.exports: $Exports<'lodash.camelcase'>;
}
declare module 'lodash.camelcase/index.js' {
  declare module.exports: $Exports<'lodash.camelcase'>;
}
