// flow-typed signature: 72db50ee5e563a58353932a69f32132b
// flow-typed version: <<STUB>>/lodash.startcase_v4.4.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.startcase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.startcase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.startcase/index' {
  declare module.exports: $Exports<'lodash.startcase'>;
}
declare module 'lodash.startcase/index.js' {
  declare module.exports: $Exports<'lodash.startcase'>;
}
