// flow-typed signature: 39f21d8284e71c128204f9c4815cf763
// flow-typed version: <<STUB>>/lodash.kebabcase_v4.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.kebabcase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.kebabcase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.kebabcase/index' {
  declare module.exports: $Exports<'lodash.kebabcase'>;
}
declare module 'lodash.kebabcase/index.js' {
  declare module.exports: $Exports<'lodash.kebabcase'>;
}
