// flow-typed signature: 89f2ea917e7b6d477cab033203bc4f18
// flow-typed version: <<STUB>>/marksy_vlatest/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'marksy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'marksy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'marksy/components' {
  declare module.exports: any;
}

declare module 'marksy/lib/components' {
  declare module.exports: any;
}

declare module 'marksy/lib/createRenderer' {
  declare module.exports: any;
}

declare module 'marksy/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'marksy/components.js' {
  declare module.exports: $Exports<'marksy/components'>;
}
declare module 'marksy/lib/components.js' {
  declare module.exports: $Exports<'marksy/lib/components'>;
}
declare module 'marksy/lib/createRenderer.js' {
  declare module.exports: $Exports<'marksy/lib/createRenderer'>;
}
declare module 'marksy/lib/index.js' {
  declare module.exports: $Exports<'marksy/lib/index'>;
}
