// flow-typed signature: 4ce9cf890fdaeaa3f2a05100cf56de49
// flow-typed version: <<STUB>>/material-design-icons_v3.0.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-design-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-design-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-design-icons/gulpfile.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-design-icons/gulpfile.babel.js' {
  declare module.exports: $Exports<'material-design-icons/gulpfile.babel'>;
}
declare module 'material-design-icons/index' {
  declare module.exports: $Exports<'material-design-icons'>;
}
declare module 'material-design-icons/index.js' {
  declare module.exports: $Exports<'material-design-icons'>;
}
