// flow-typed signature: fd14e247d5036ff9c21e17bacee5ac51
// flow-typed version: <<STUB>>/memoize-one_v4.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memoize-one'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'memoize-one' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'memoize-one/dist/memoize-one.cjs' {
  declare module.exports: any;
}

declare module 'memoize-one/dist/memoize-one.esm' {
  declare module.exports: any;
}

declare module 'memoize-one/dist/memoize-one' {
  declare module.exports: any;
}

declare module 'memoize-one/dist/memoize-one.min' {
  declare module.exports: any;
}

declare module 'memoize-one/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'memoize-one/dist/memoize-one.cjs.js' {
  declare module.exports: $Exports<'memoize-one/dist/memoize-one.cjs'>;
}
declare module 'memoize-one/dist/memoize-one.esm.js' {
  declare module.exports: $Exports<'memoize-one/dist/memoize-one.esm'>;
}
declare module 'memoize-one/dist/memoize-one.js' {
  declare module.exports: $Exports<'memoize-one/dist/memoize-one'>;
}
declare module 'memoize-one/dist/memoize-one.min.js' {
  declare module.exports: $Exports<'memoize-one/dist/memoize-one.min'>;
}
declare module 'memoize-one/src/index.js' {
  declare module.exports: $Exports<'memoize-one/src/index'>;
}
