// flow-typed signature: f17ecf474b1e3d5ed16650470f5de74b
// flow-typed version: <<STUB>>/mineral-ui-tokens_v0.3.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mineral-ui-tokens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mineral-ui-tokens' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mineral-ui-tokens/all' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/blue' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/brand' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/bronze' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/dusk' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/all' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/blue' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/brand' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/bronze' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/dusk' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/gray' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/green' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/index' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/indigo' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/magenta' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/palette' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/purple' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/red' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/sky' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/slate' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/teal' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/es/tokens' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/gray' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/green' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/indigo' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/magenta' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/palette' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/purple' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/red' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/sky' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/slate' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/teal' {
  declare module.exports: any;
}

declare module 'mineral-ui-tokens/tokens' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mineral-ui-tokens/all.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/all'>;
}
declare module 'mineral-ui-tokens/blue.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/blue'>;
}
declare module 'mineral-ui-tokens/brand.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/brand'>;
}
declare module 'mineral-ui-tokens/bronze.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/bronze'>;
}
declare module 'mineral-ui-tokens/dusk.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/dusk'>;
}
declare module 'mineral-ui-tokens/es/all.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/all'>;
}
declare module 'mineral-ui-tokens/es/blue.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/blue'>;
}
declare module 'mineral-ui-tokens/es/brand.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/brand'>;
}
declare module 'mineral-ui-tokens/es/bronze.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/bronze'>;
}
declare module 'mineral-ui-tokens/es/dusk.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/dusk'>;
}
declare module 'mineral-ui-tokens/es/gray.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/gray'>;
}
declare module 'mineral-ui-tokens/es/green.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/green'>;
}
declare module 'mineral-ui-tokens/es/index.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/index'>;
}
declare module 'mineral-ui-tokens/es/indigo.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/indigo'>;
}
declare module 'mineral-ui-tokens/es/magenta.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/magenta'>;
}
declare module 'mineral-ui-tokens/es/palette.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/palette'>;
}
declare module 'mineral-ui-tokens/es/purple.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/purple'>;
}
declare module 'mineral-ui-tokens/es/red.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/red'>;
}
declare module 'mineral-ui-tokens/es/sky.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/sky'>;
}
declare module 'mineral-ui-tokens/es/slate.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/slate'>;
}
declare module 'mineral-ui-tokens/es/teal.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/teal'>;
}
declare module 'mineral-ui-tokens/es/tokens.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/es/tokens'>;
}
declare module 'mineral-ui-tokens/gray.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/gray'>;
}
declare module 'mineral-ui-tokens/green.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/green'>;
}
declare module 'mineral-ui-tokens/index' {
  declare module.exports: $Exports<'mineral-ui-tokens'>;
}
declare module 'mineral-ui-tokens/index.js' {
  declare module.exports: $Exports<'mineral-ui-tokens'>;
}
declare module 'mineral-ui-tokens/indigo.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/indigo'>;
}
declare module 'mineral-ui-tokens/magenta.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/magenta'>;
}
declare module 'mineral-ui-tokens/palette.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/palette'>;
}
declare module 'mineral-ui-tokens/purple.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/purple'>;
}
declare module 'mineral-ui-tokens/red.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/red'>;
}
declare module 'mineral-ui-tokens/sky.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/sky'>;
}
declare module 'mineral-ui-tokens/slate.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/slate'>;
}
declare module 'mineral-ui-tokens/teal.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/teal'>;
}
declare module 'mineral-ui-tokens/tokens.js' {
  declare module.exports: $Exports<'mineral-ui-tokens/tokens'>;
}
