// flow-typed signature: 0e38b105401ce7d2a06fad480cf5a74c
// flow-typed version: <<STUB>>/mustache_v2.3.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mustache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mustache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mustache/mustache' {
  declare module.exports: any;
}

declare module 'mustache/mustache.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mustache/mustache.js' {
  declare module.exports: $Exports<'mustache/mustache'>;
}
declare module 'mustache/mustache.min.js' {
  declare module.exports: $Exports<'mustache/mustache.min'>;
}
