// flow-typed signature: e32d340a24c7565bfc59dda1db1b33d9
// flow-typed version: <<STUB>>/prepend-file_v1.3.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prepend-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prepend-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'prepend-file/index' {
  declare module.exports: $Exports<'prepend-file'>;
}
declare module 'prepend-file/index.js' {
  declare module.exports: $Exports<'prepend-file'>;
}
