// flow-typed signature: b60437f267a0843f60bd70eccd660bcb
// flow-typed version: <<STUB>>/pretty-bytes_v5.1.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-bytes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-bytes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pretty-bytes/index' {
  declare module.exports: $Exports<'pretty-bytes'>;
}
declare module 'pretty-bytes/index.js' {
  declare module.exports: $Exports<'pretty-bytes'>;
}
