// flow-typed signature: b92755c7890783d29b88cfbb63754cbe
// flow-typed version: <<STUB>>/react-fast-compare_v2.0.4/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fast-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fast-compare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-fast-compare/index' {
  declare module.exports: $Exports<'react-fast-compare'>;
}
declare module 'react-fast-compare/index.js' {
  declare module.exports: $Exports<'react-fast-compare'>;
}
