// flow-typed signature: abf078dda4fb380b7f50bbf3b6a040d6
// flow-typed version: <<STUB>>/react-docgen-loader_v2.9.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-docgen-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-docgen-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-docgen-loader/index' {
  declare module.exports: $Exports<'react-docgen-loader'>;
}
declare module 'react-docgen-loader/index.js' {
  declare module.exports: $Exports<'react-docgen-loader'>;
}
