// flow-typed signature: 4ad56acb1ffe1fffc5a6962211a66c85
// flow-typed version: <<STUB>>/react-popper_v0.10.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-popper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-popper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-popper/dist/react-popper' {
  declare module.exports: any;
}

declare module 'react-popper/dist/react-popper.min' {
  declare module.exports: any;
}

declare module 'react-popper/dist/react-popper.umd' {
  declare module.exports: any;
}

declare module 'react-popper/dist/react-popper.umd.min' {
  declare module.exports: any;
}

declare module 'react-popper/lib/Arrow' {
  declare module.exports: any;
}

declare module 'react-popper/lib/Manager' {
  declare module.exports: any;
}

declare module 'react-popper/lib/Popper' {
  declare module.exports: any;
}

declare module 'react-popper/lib/react-popper' {
  declare module.exports: any;
}

declare module 'react-popper/lib/Target' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-popper/dist/react-popper.js' {
  declare module.exports: $Exports<'react-popper/dist/react-popper'>;
}
declare module 'react-popper/dist/react-popper.min.js' {
  declare module.exports: $Exports<'react-popper/dist/react-popper.min'>;
}
declare module 'react-popper/dist/react-popper.umd.js' {
  declare module.exports: $Exports<'react-popper/dist/react-popper.umd'>;
}
declare module 'react-popper/dist/react-popper.umd.min.js' {
  declare module.exports: $Exports<'react-popper/dist/react-popper.umd.min'>;
}
declare module 'react-popper/lib/Arrow.js' {
  declare module.exports: $Exports<'react-popper/lib/Arrow'>;
}
declare module 'react-popper/lib/Manager.js' {
  declare module.exports: $Exports<'react-popper/lib/Manager'>;
}
declare module 'react-popper/lib/Popper.js' {
  declare module.exports: $Exports<'react-popper/lib/Popper'>;
}
declare module 'react-popper/lib/react-popper.js' {
  declare module.exports: $Exports<'react-popper/lib/react-popper'>;
}
declare module 'react-popper/lib/Target.js' {
  declare module.exports: $Exports<'react-popper/lib/Target'>;
}
