// flow-typed signature: 7aa4dcb3b794da00eb2450c72ac1c212
// flow-typed version: <<STUB>>/react-live_v1.8.0-2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-live'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-live' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-live/dist/react-live.es' {
  declare module.exports: any;
}

declare module 'react-live/dist/react-live' {
  declare module.exports: any;
}

declare module 'react-live/dist/react-live.min' {
  declare module.exports: any;
}

declare module 'react-live/lib/components/Editor/index' {
  declare module.exports: any;
}

declare module 'react-live/lib/components/Editor/Style' {
  declare module.exports: any;
}

declare module 'react-live/lib/components/Live/LiveEditor' {
  declare module.exports: any;
}

declare module 'react-live/lib/components/Live/LiveError' {
  declare module.exports: any;
}

declare module 'react-live/lib/components/Live/LivePreview' {
  declare module.exports: any;
}

declare module 'react-live/lib/components/Live/LiveProvider' {
  declare module.exports: any;
}

declare module 'react-live/lib/constants/css' {
  declare module.exports: any;
}

declare module 'react-live/lib/hoc/withLive' {
  declare module.exports: any;
}

declare module 'react-live/lib/index' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/cn' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/getIndent' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/htmlToPlain' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/normalizeCode' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/normalizeHtml' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/prism' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/test/cn.test' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/test/errorBoundary.test' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/test/htmlToPlain.test' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/test/normalizeHtml.test' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/test/prism.test' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/test/transpile.test' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/transpile/errorBoundary' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/transpile/evalCode' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/transpile/index' {
  declare module.exports: any;
}

declare module 'react-live/lib/utils/transpile/transform' {
  declare module.exports: any;
}

declare module 'react-live/lib/vendor/selection-range/index' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Editor/index' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Editor/Style' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Live/LiveEditor' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Live/LiveError' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Live/LivePreview' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Live/LiveProvider' {
  declare module.exports: any;
}

declare module 'react-live/src/constants/css' {
  declare module.exports: any;
}

declare module 'react-live/src/hoc/withLive' {
  declare module.exports: any;
}

declare module 'react-live/src/index' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/cn' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/getIndent' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/htmlToPlain' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/normalizeCode' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/normalizeHtml' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/prism' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/test/cn.test' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/test/errorBoundary.test' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/test/htmlToPlain.test' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/test/normalizeHtml.test' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/test/prism.test' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/test/transpile.test' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/transpile/errorBoundary' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/transpile/evalCode' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/transpile/index' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/transpile/transform' {
  declare module.exports: any;
}

declare module 'react-live/src/vendor/selection-range/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-live/dist/react-live.es.js' {
  declare module.exports: $Exports<'react-live/dist/react-live.es'>;
}
declare module 'react-live/dist/react-live.js' {
  declare module.exports: $Exports<'react-live/dist/react-live'>;
}
declare module 'react-live/dist/react-live.min.js' {
  declare module.exports: $Exports<'react-live/dist/react-live.min'>;
}
declare module 'react-live/lib/components/Editor/index.js' {
  declare module.exports: $Exports<'react-live/lib/components/Editor/index'>;
}
declare module 'react-live/lib/components/Editor/Style.js' {
  declare module.exports: $Exports<'react-live/lib/components/Editor/Style'>;
}
declare module 'react-live/lib/components/Live/LiveEditor.js' {
  declare module.exports: $Exports<'react-live/lib/components/Live/LiveEditor'>;
}
declare module 'react-live/lib/components/Live/LiveError.js' {
  declare module.exports: $Exports<'react-live/lib/components/Live/LiveError'>;
}
declare module 'react-live/lib/components/Live/LivePreview.js' {
  declare module.exports: $Exports<'react-live/lib/components/Live/LivePreview'>;
}
declare module 'react-live/lib/components/Live/LiveProvider.js' {
  declare module.exports: $Exports<'react-live/lib/components/Live/LiveProvider'>;
}
declare module 'react-live/lib/constants/css.js' {
  declare module.exports: $Exports<'react-live/lib/constants/css'>;
}
declare module 'react-live/lib/hoc/withLive.js' {
  declare module.exports: $Exports<'react-live/lib/hoc/withLive'>;
}
declare module 'react-live/lib/index.js' {
  declare module.exports: $Exports<'react-live/lib/index'>;
}
declare module 'react-live/lib/utils/cn.js' {
  declare module.exports: $Exports<'react-live/lib/utils/cn'>;
}
declare module 'react-live/lib/utils/getIndent.js' {
  declare module.exports: $Exports<'react-live/lib/utils/getIndent'>;
}
declare module 'react-live/lib/utils/htmlToPlain.js' {
  declare module.exports: $Exports<'react-live/lib/utils/htmlToPlain'>;
}
declare module 'react-live/lib/utils/normalizeCode.js' {
  declare module.exports: $Exports<'react-live/lib/utils/normalizeCode'>;
}
declare module 'react-live/lib/utils/normalizeHtml.js' {
  declare module.exports: $Exports<'react-live/lib/utils/normalizeHtml'>;
}
declare module 'react-live/lib/utils/prism.js' {
  declare module.exports: $Exports<'react-live/lib/utils/prism'>;
}
declare module 'react-live/lib/utils/test/cn.test.js' {
  declare module.exports: $Exports<'react-live/lib/utils/test/cn.test'>;
}
declare module 'react-live/lib/utils/test/errorBoundary.test.js' {
  declare module.exports: $Exports<'react-live/lib/utils/test/errorBoundary.test'>;
}
declare module 'react-live/lib/utils/test/htmlToPlain.test.js' {
  declare module.exports: $Exports<'react-live/lib/utils/test/htmlToPlain.test'>;
}
declare module 'react-live/lib/utils/test/normalizeHtml.test.js' {
  declare module.exports: $Exports<'react-live/lib/utils/test/normalizeHtml.test'>;
}
declare module 'react-live/lib/utils/test/prism.test.js' {
  declare module.exports: $Exports<'react-live/lib/utils/test/prism.test'>;
}
declare module 'react-live/lib/utils/test/transpile.test.js' {
  declare module.exports: $Exports<'react-live/lib/utils/test/transpile.test'>;
}
declare module 'react-live/lib/utils/transpile/errorBoundary.js' {
  declare module.exports: $Exports<'react-live/lib/utils/transpile/errorBoundary'>;
}
declare module 'react-live/lib/utils/transpile/evalCode.js' {
  declare module.exports: $Exports<'react-live/lib/utils/transpile/evalCode'>;
}
declare module 'react-live/lib/utils/transpile/index.js' {
  declare module.exports: $Exports<'react-live/lib/utils/transpile/index'>;
}
declare module 'react-live/lib/utils/transpile/transform.js' {
  declare module.exports: $Exports<'react-live/lib/utils/transpile/transform'>;
}
declare module 'react-live/lib/vendor/selection-range/index.js' {
  declare module.exports: $Exports<'react-live/lib/vendor/selection-range/index'>;
}
declare module 'react-live/src/components/Editor/index.js' {
  declare module.exports: $Exports<'react-live/src/components/Editor/index'>;
}
declare module 'react-live/src/components/Editor/Style.js' {
  declare module.exports: $Exports<'react-live/src/components/Editor/Style'>;
}
declare module 'react-live/src/components/Live/LiveEditor.js' {
  declare module.exports: $Exports<'react-live/src/components/Live/LiveEditor'>;
}
declare module 'react-live/src/components/Live/LiveError.js' {
  declare module.exports: $Exports<'react-live/src/components/Live/LiveError'>;
}
declare module 'react-live/src/components/Live/LivePreview.js' {
  declare module.exports: $Exports<'react-live/src/components/Live/LivePreview'>;
}
declare module 'react-live/src/components/Live/LiveProvider.js' {
  declare module.exports: $Exports<'react-live/src/components/Live/LiveProvider'>;
}
declare module 'react-live/src/constants/css.js' {
  declare module.exports: $Exports<'react-live/src/constants/css'>;
}
declare module 'react-live/src/hoc/withLive.js' {
  declare module.exports: $Exports<'react-live/src/hoc/withLive'>;
}
declare module 'react-live/src/index.js' {
  declare module.exports: $Exports<'react-live/src/index'>;
}
declare module 'react-live/src/utils/cn.js' {
  declare module.exports: $Exports<'react-live/src/utils/cn'>;
}
declare module 'react-live/src/utils/getIndent.js' {
  declare module.exports: $Exports<'react-live/src/utils/getIndent'>;
}
declare module 'react-live/src/utils/htmlToPlain.js' {
  declare module.exports: $Exports<'react-live/src/utils/htmlToPlain'>;
}
declare module 'react-live/src/utils/normalizeCode.js' {
  declare module.exports: $Exports<'react-live/src/utils/normalizeCode'>;
}
declare module 'react-live/src/utils/normalizeHtml.js' {
  declare module.exports: $Exports<'react-live/src/utils/normalizeHtml'>;
}
declare module 'react-live/src/utils/prism.js' {
  declare module.exports: $Exports<'react-live/src/utils/prism'>;
}
declare module 'react-live/src/utils/test/cn.test.js' {
  declare module.exports: $Exports<'react-live/src/utils/test/cn.test'>;
}
declare module 'react-live/src/utils/test/errorBoundary.test.js' {
  declare module.exports: $Exports<'react-live/src/utils/test/errorBoundary.test'>;
}
declare module 'react-live/src/utils/test/htmlToPlain.test.js' {
  declare module.exports: $Exports<'react-live/src/utils/test/htmlToPlain.test'>;
}
declare module 'react-live/src/utils/test/normalizeHtml.test.js' {
  declare module.exports: $Exports<'react-live/src/utils/test/normalizeHtml.test'>;
}
declare module 'react-live/src/utils/test/prism.test.js' {
  declare module.exports: $Exports<'react-live/src/utils/test/prism.test'>;
}
declare module 'react-live/src/utils/test/transpile.test.js' {
  declare module.exports: $Exports<'react-live/src/utils/test/transpile.test'>;
}
declare module 'react-live/src/utils/transpile/errorBoundary.js' {
  declare module.exports: $Exports<'react-live/src/utils/transpile/errorBoundary'>;
}
declare module 'react-live/src/utils/transpile/evalCode.js' {
  declare module.exports: $Exports<'react-live/src/utils/transpile/evalCode'>;
}
declare module 'react-live/src/utils/transpile/index.js' {
  declare module.exports: $Exports<'react-live/src/utils/transpile/index'>;
}
declare module 'react-live/src/utils/transpile/transform.js' {
  declare module.exports: $Exports<'react-live/src/utils/transpile/transform'>;
}
declare module 'react-live/src/vendor/selection-range/index.js' {
  declare module.exports: $Exports<'react-live/src/vendor/selection-range/index'>;
}
