// flow-typed signature: 10509a3f790231d4ea5cdafa05fb7bab
// flow-typed version: <<STUB>>/scroll-into-view-if-needed_v1.5.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scroll-into-view-if-needed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scroll-into-view-if-needed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scroll-into-view-if-needed/dist/bundle' {
  declare module.exports: any;
}

declare module 'scroll-into-view-if-needed/dist/calculate' {
  declare module.exports: any;
}

declare module 'scroll-into-view-if-needed/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scroll-into-view-if-needed/dist/bundle.js' {
  declare module.exports: $Exports<'scroll-into-view-if-needed/dist/bundle'>;
}
declare module 'scroll-into-view-if-needed/dist/calculate.js' {
  declare module.exports: $Exports<'scroll-into-view-if-needed/dist/calculate'>;
}
declare module 'scroll-into-view-if-needed/dist/index.js' {
  declare module.exports: $Exports<'scroll-into-view-if-needed/dist/index'>;
}
