// flow-typed signature: bf6264056a3264e41c59abd7fe8348cc
// flow-typed version: <<STUB>>/lodash/flatten_vlatest/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash/flatten'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash/flatten' {
  declare module.exports: any;
}
